<a href="https://colab.research.google.com/github/MounikaBoddu1999/Neural_networks_coursework/blob/main/Mounika_Boddu_ICP2_700766342.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
class Employee:
    """
    Generic Employee class with name, family, salary, and department.
    """

    # Class variable to count the number of Employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @staticmethod
    def average_salary(employees):
        """
        Function to calculate the average salary of the given employees.
        """
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / Employee.employee_count if Employee.employee_count > 0 else 0


class FulltimeEmployee(Employee):
    """
    FulltimeEmployee is a subclass of Employee.
    """

    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


def main():
    employees = []

    # Creating instances of FulltimeEmployee and Employee
    fulltime_emp1 = FulltimeEmployee("Alice", "Smith", 120000, "Engineering")
    fulltime_emp2 = FulltimeEmployee("Bob", "Johnson", 90000, "Finance")
    emp1 = Employee("Charlie", "Brown", 75000, "Marketing")
    emp2 = Employee("Daisy", "Williams", 85000, "HR")

    # Adding employees to the list
    employees.extend([fulltime_emp1, fulltime_emp2, emp1, emp2])

    # Printing employee details and average salary
    print(f"Total number of employees: {Employee.employee_count}")
    print(f"Average salary: ${Employee.average_salary(employees):.2f}")

    # Example of accessing attributes from an instance
    for emp in employees:
        print(f"Employee: {emp.name}, Family: {emp.family}, Department: {emp.department}, Salary: ${emp.salary}")


if __name__ == "__main__":
    main()


Total number of employees: 4
Average salary: $92500.00
Employee: Alice, Family: Smith, Department: Engineering, Salary: $120000
Employee: Bob, Family: Johnson, Department: Finance, Salary: $90000
Employee: Charlie, Family: Brown, Department: Marketing, Salary: $75000
Employee: Daisy, Family: Williams, Department: HR, Salary: $85000


In [19]:
import numpy as np

#  a random vector of size 20 with floats in the range 1-20
vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
vector_new = vector.reshape(4, 5)  # Changed 'random_vector' to 'vector'
print(vector_new)

# Replace the maximum value in each row with 0 (without using a for loop)
vector_new[np.arange(vector_new.shape[0]), vector_new.argmax(axis=1)] = 0

# Display the  array
print(vector_new)


[[ 4.38077484  5.34896562 17.64119115  6.07887685  7.15282658]
 [14.76383432  9.56362884  2.87560452 10.17689909  1.75174032]
 [ 8.2644778  19.13705889  6.27431331  6.86361772  4.75509623]
 [10.7208136  14.89293003 10.70433221  1.50132677 11.96810278]]
[[ 4.38077484  5.34896562  0.          6.07887685  7.15282658]
 [ 0.          9.56362884  2.87560452 10.17689909  1.75174032]
 [ 8.2644778   0.          6.27431331  6.86361772  4.75509623]
 [10.7208136   0.         10.70433221  1.50132677 11.96810278]]
